version: '2'
services:
  bus115:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
    links:
     - bus115-db-mysql

  bus115-db-mysql:
    image: "mysql:5.7"
    env_file:
     - ./config/app.env
    volumes:
      - $VOLUME_DIR/data/volume/mysql:/var/lib/mysql
      - $VOLUME_DIR/data/volume/logs/mysql:/var/log/mysql
    ports:
      - '3306:3306'

  bus115-phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.0-1
    ports:
      - "8088:80"
    environment:
      - PMA_HOST=bus115-db-mysql
