<?php

namespace Bus115\Repository;

/**
 * GeocodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeocodeRepository extends \Doctrine\ORM\EntityRepository
{
}
